### ISSUE TITLE
train.py Process finished with exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by c1a1o1** [LynnHo/AttGAN-Tensorflow#1]
train.py Process finished with exit code -1073740791 (0xC0000409)

**Comment by c1a1o1** [comment]
tensorflow 1.7

**Comment by LynnHo** [comment]
@c1a1o1 Is there any other output? What's the full command you used?

**Comment by c1a1o1** [comment]
my problem！Thank you！

**Comment by BNAadministrator3** [comment]
Guy what is your problem? I met the same.

**Comment by huangbiubiu** [comment]
Same problem too. There was nothing error output. Could you offer your workaround?

**Comment by LynnHo** [comment]
@huangbiubiu which command did you use?
