### ISSUE TITLE
I want to use this checkpoint in ios as mlmodel, 

### ISSUE THREAD

**Issue by xyzdcgan** [LynnHo/AttGAN-Tensorflow#12]
Hello, i converted the checkpoint model to .pb file and then want to convert it to .mlmodel file, at present  i have .pb file, and while conversion to .mlmodel it has an error 

ValueError: graph_def is invalid at node u'Genc/Conv/BatchNorm/AssignMovingAvg': Input tensor 'Genc/Conv/BatchNorm/moving_mean:0' Cannot convert a tensor of type float32 to an input of type float32_ref.

And the code for it is:

import tfcoreml
# Supply a dictionary of input tensors' name and shape (with batch axis)
input_tensor_shapes = {"input:0": [1, 224, 224, 3]} # batch size is 1
# TF graph definition
tf_model_path = './frozen_graph.pb'
# Output CoreML model path
coreml_model_file = './frozen_graph_ios.mlmodel'
# The TF model's ouput tensor name
output_tensor_names = ['final_result:0']

# Call the converter. This may take a while
coreml_model = tfcoreml.convert (
tf_model_path=tf_model_path,
mlmodel_path=coreml_model_file,
input_name_shape_dict=input_tensor_shapes,
output_feature_names=output_tensor_names,
image_input_names = ['input:0'],
red_bias = -1,
green_bias = -1,
blue_bias = -1,
image_scale = 2.0/255.0)

please tell me how i can convert it to .mlmodel

**Comment by LynnHo** [comment]
@xyzdcgan I am sorry I have no experience on mlmodel.
