### ISSUE TITLE
Facial Attribute

### ISSUE THREAD

**Issue by xyzdcgan** [LynnHo/AttGAN-Tensorflow#14]
Hello, @LynnHo  Can you tell how we can do facial feature extraction, means if input any image of face and then how we can get the 40 facial attribute from that. 

Thanks.

**Comment by LynnHo** [comment]
@xyzdcgan You should train a 40 attribute model.

**Comment by xyzdcgan** [comment]
But how @LynnHo Using what i can get 40 attribute of face.

**Comment by LynnHo** [comment]
@xyzdcgan The Celeba dataset contains 40 attribute annotations.

**Comment by xyzdcgan** [comment]
But i want 40 attribute in custom image dataset. @LynnHo not of celeba

**Comment by LynnHo** [comment]
@xyzdcgan One solution is to predict 40 attributes of your custom dataset using a well-trained attribute predictor (trained on Celeba or others).

**Comment by xyzdcgan** [comment]
okay, do you know any attribute predictor..! @LynnHo

**Comment by LynnHo** [comment]
@xyzdcgan I am not an expert on attribute prediction. You may refer to the state-of-the-art papers for attribute prediction.

**Comment by xyzdcgan** [comment]
Yes not an issue @LynnHo will find some way for that, and find facial attribute
