### ISSUE TITLE
training using celeba, testing using custom dataset

### ISSUE THREAD

**Issue by maliho0803** [LynnHo/AttGAN-Tensorflow#17]
if I using the model trained by celeba to test my custom images, will it get good results?

**Comment by maliho0803** [comment]
if I using the model trained by celeba to test my custom images, will it get good results?

**Comment by CastellanLiu** [comment]
I should remind that this model is trained by the aligned CelebA dataset. The results on your custom images may look weird on attributes such as Mouth_Slightly_Open, Mustache, etc., but should be okay on attributes like Hair_Color, Pale_Skin if the face is the main part of your image.
Maybe your can try training the model on the unaligned CelebA dataset.

**Comment by maliho0803** [comment]
@[CastellanLiu](/CastellanLiu)thank you for your reply, if I aligned my custom dataset, may it will get better results? and more, if the methods of gan can not work well out of training  data?

**Comment by LynnHo** [comment]
@maliho0803 First, you should align your dataset as the CelebA manner. Second, you should provide accurate attributes of your dataset. It is inconvenient for users to do these and therefore a drawback of this project. I will improve it when I have free time. Besides, I test the model on LFW and it works like on CelebA.

**Comment by maliho0803** [comment]
@LynnHo when testing, needed images labeled attributes?

**Comment by LynnHo** [comment]
> @LynnHo when testing, needed images labeled attributes?

Yes.

**Comment by maliho0803** [comment]
@LynnHo how do you labeled LFW datasets?

**Comment by LynnHo** [comment]
> @LynnHo how do you labeled LFW datasets?

I use an attribute predictor trained on CelebA.

**Comment by huxianer** [comment]
@LynnHo Could you share the predictor trained on CelebA?Thank you for any help!

**Comment by CastellanLiu** [comment]
Maybe you can find what you want in #11

**Comment by LynnHo** [comment]
@huxianer Yes, as @CastellanLiu said, you may refer to #11. Or [here](https://github.com/csmliu/STGAN/tree/master/att_classification) is an attribute classifier from [STGAN](https://github.com/csmliu/STGAN) which has the same protocol of our AttGAN.

**Comment by huxianer** [comment]
Thanks!

**Comment by Varshul** [comment]
hey @maliho0803 , did you try this on your custom dataset? If yes, then were the results satisfying? Also, can you share your the modified files?
