### ISSUE TITLE
Unable to use different number of images

### ISSUE THREAD

**Issue by githubusername001** [LynnHo/AttGAN-Tensorflow#18]
Hello. I am using **hd - celeba 384** dataset with provided **384_shortcut1_inject1_none_hd** model. I am trying to use custom number of images instead of using all 202599 images. I tried to do the following: modify **list_attr_celeba.txt** file to only include first 20 images and put these 20 images in **./data/img_crop_celeba/*.jpg**. However, this is the error I get: 

`TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.
`

I also tried to train with only 20 images and get the same error. I get no errors when running train/test for all 202599 images.

**Comment by LynnHo** [comment]
@githubusername001 Does the code work if you don't modify the image number? Or can you provide the part you have modified?

**Comment by CastellanLiu** [comment]
This `TypeError` may be caused by imporper `list_attr_celeba.txt` file (your custom `list_attr_celeba.txt` should have 40 labels in each line as the raw one).
Also note that you should modify the numbers in data.py to fit your dataset.
https://github.com/LynnHo/AttGAN-Tensorflow/blob/1792df6851c7e4d09bf0f1c9f5155fd7b0618d18/data.py#L197-L208

**Comment by githubusername001** [comment]
Thanks, the issue was indeed with modifying **data.py** file. I tried changing the values, however, I still encounter some problems. 

Currently, I have first 20 pictures (000001.png - 000020.png) pictures in **img_crop_celeba** and 20 corresponding lines of labels in **list_attr_celeba.txt**. I also modified **data.py** in the following way:

```
if part == 'test': 
     drop_remainder = False 
     shuffle = False 
     repeat = 1 
     img_paths = img_paths[0:] 
     labels = labels[0:] 
 elif part == 'val': 
     img_paths = img_paths[0:] 
     labels = labels[0:] 
 else: 
     img_paths = img_paths[0:] 
     labels = labels[0:]
```

The program seems to work fine now. However, when running the test.py in terminal I have the following output: 
`182638.png done! --- 182657.png done!`

Rather then something like this:

`000001.png done! --- 000020.png done!`

Could you please explain what each of these values in **data.py** is responsible for.

**Comment by githubusername001** [comment]
> @githubusername001 Does the code work if you don't modify the image number? Or can you provide the part you have modified?

It works with all 202599 images and I only modified **list_attr_celeba.txt**.

**Comment by CastellanLiu** [comment]
The filename is set in the last rows of test.py

**Comment by CastellanLiu** [comment]
The values in data.py split the dataset into train/val/test parts, i.e., the first 182000 images are used as training set, the following 637 are prepared for validation, and the rest ones are used for test.

**Comment by githubusername001** [comment]
If I only need to run test.py on a pretrained model do I still need to allow some images for train and validation? For example, if I want to run test.py on 50 images from the dataset how many extra images I should allow for train and validation?

**Comment by CastellanLiu** [comment]
No, train/val sets are prepared for training. You can just delete the `182637` in test.py

**Comment by LynnHo** [comment]
> Thanks, the issue was indeed with modifying **data.py** file. I tried changing the values, however, I still encounter some problems.
> 
> Currently, I have first 20 pictures (000001.png - 000020.png) pictures in **img_crop_celeba** and 20 corresponding lines of labels in **list_attr_celeba.txt**. I also modified **data.py** in the following way:
> 
> ```
> if part == 'test': 
>      drop_remainder = False 
>      shuffle = False 
>      repeat = 1 
>      img_paths = img_paths[0:] 
>      labels = labels[0:] 
>  elif part == 'val': 
>      img_paths = img_paths[0:] 
>      labels = labels[0:] 
>  else: 
>      img_paths = img_paths[0:] 
>      labels = labels[0:]
> ```
> The program seems to work fine now. However, when running the test.py in terminal I have the following output:
> `182638.png done! --- 182657.png done!`
> 
> Rather then something like this:
> 
> `000001.png done! --- 000020.png done!`
> 
> Could you please explain what each of these values in **data.py** is responsible for.

This is a drawback of my code, the printed name is hard coded as seen from below. That means `182638.png` above is actually `000001.png`.
https://github.com/LynnHo/AttGAN-Tensorflow/blob/1792df6851c7e4d09bf0f1c9f5155fd7b0618d18/test.py#L106-L108

Therefore, it is enough to just modify here as you did before.
https://github.com/LynnHo/AttGAN-Tensorflow/blob/1792df6851c7e4d09bf0f1c9f5155fd7b0618d18/data.py#L197-L202

**Comment by githubusername001** [comment]
That makes sense, thank you. Also, not to spam issues I will just ask here. What do I need to modify to save each new image separately rather than all in one file. I tried changing some code in lines 84 - 105 in **test.py**. However, I get different errors such as `'Tensor' object has no attribute`.
