### ISSUE TITLE
Compatible for multiple GPU training?

### ISSUE THREAD

**Issue by lishali** [LynnHo/AttGAN-Tensorflow#20]
Hi there, I'm trying to enable training on a 8 GPU cluster.  It looks like I should alter the tf.session code in Tfutils but wanted to make sure it was not already solved.  Thanks!

**Comment by LynnHo** [comment]
@lishali This code currently does not support multi-GPU.

**Comment by lishali** [comment]
Ok, thanks for the response, will see if I can add that capability.

**Comment by LynnHo** [comment]
@lishali https://github.com/elvisyjlin/AttGAN-PyTorch, this unofficial repo with PyTorch seems to support multi-GPU training. Thanks for @elvisyjlin.
