### ISSUE TITLE
Parameters for replicating quantitative results

### ISSUE THREAD

**Issue by e-271** [LynnHo/AttGAN-Tensorflow#27]
Hi, thanks for your great work! I am trying to replicate your quantitative results, but currently only get about ~46% accuracy. What parameters do you use to get these results?

Currently I have:
200 epochs
im_size=64
inject=0
skip_connections=1
reconstruction_loss=10

**Comment by LynnHo** [comment]
@e-271 You can try `skip_connections=0` for 64-model. However, some details of the code are different from the paper (for example, the 64-model in paper use layer normalization), therefore, the results will still have a difference. Or you can refer to #11 for a 128 model with similar accuracy.
