### ISSUE TITLE
remove glasses

### ISSUE THREAD

**Issue by Retrospection** [LynnHo/AttGAN-Tensorflow#3]
Hi, I noticed that you only gave the result of add glasses to a person's face, what should I do if I want to use this network to remove glasses from a person's face?

**Comment by LynnHo** [comment]
@Retrospection Just input a `zero` attribute value for `Eyeglasses`. However, removing eyeglasses is very difficult, our method works on removing thin rim glasses but might fail on sunglasses. To our knowledge, current methods for facial attribute manipulation cannot handle the eyeglasses removing very well.

**Comment by Retrospection** [comment]
@LynnHo Thanks for your kindness!
