### ISSUE TITLE
Testing of generator.pb

### ISSUE THREAD

**Issue by shbnm21** [LynnHo/AttGAN-Tensorflow#32]
How to test generator.pb so as to check it gives same results as the trained model(.ckpt file)

**Comment by shbnm21** [comment]
I have visualized results of .pb file on tensorboard and it is similar to trained model.
I want to test .pb file on images.
Can I use test.py script to test .pb file.
If yes what changes I need to make to test .pb file.

**Comment by LynnHo** [comment]
@shbnm21 You can just use .pb file following README.

**Comment by shbnm21** [comment]
Ok,thank u.
And thank u so much for providing python script for converting trained model into .pb file.
