### ISSUE TITLE
Why attributes are encoded into [-1, 1] not [0, 1]

### ISSUE THREAD

**Issue by ChengBinJin** [LynnHo/AttGAN-Tensorflow#35]
@LynnHo 
Hi, I read your code theses days, and I wonder about why the label of attributes has to map into [-1, 1] instead of [0, 1]. It seems that it is very important and has some technical reason because you commented on three exclamation marks on that code. Could you share some experimental knowledge about this?

**Comment by LynnHo** [comment]
> @LynnHo
> Hi, I read your code theses days, and I wonder about why the label of attributes has to map into [-1, 1] instead of [0, 1]. It seems that it is very important and has some technical reason because you commented on three exclamation marks on that code. Could you share some experimental knowledge about this?

Both [-1, 1] and [0, 1] should work. But I think "-1" is better than "0" because "0" suppresses the filter directly applying on it, which produces zero activation.

**Comment by ChengBinJin** [comment]
@LynnHo I see. Thank you!

**Comment by ChengBinJin** [comment]
@LynnHo 
In the "young" attribute for example, if we map the original "0" attribute into "-1" as you said, how the network knows that we want to let the network ignore this attribute or let it go to "old" direction? I found in the "test_slide.py" code, we can directly control the attribute strength from -2 (become old) to 2 (become young). I'm afraid that if I want to control the "mouth-open" axis only by setting all other attributes to 0 (actually it will become -1), but the network could also change in the "young" axis.

**Comment by LynnHo** [comment]
@ChengBinJin You are right, actually, this is a problem. In our method, it is not sure or it cannot be controlled that, whether an "Old" person given "-1" will become "Older" or keep the same. For this problem, one solution is to train the network with "attribute difference indicator", i.e., "1" for younger, "-1" for older, and "0" to keep. You can refer to [STGAN](https://zpascal.net/cvpr2019/Liu_STGAN_A_Unified_Selective_Transfer_Network_for_Arbitrary_Image_Attribute_CVPR_2019_paper.pdf) and [RelGAN](http://openaccess.thecvf.com/content_ICCV_2019/html/Wu_RelGAN_Multi-Domain_Image-to-Image_Translation_via_Relative_Attributes_ICCV_2019_paper.html).

**Comment by ChengBinJin** [comment]
@LynnHo Thank you for your detailed explanation. I very much appreciate that you can share your knowledge about this domain.
