### ISSUE TITLE
Unable to apply the model on a new image

### ISSUE THREAD

**Issue by dlazzara** [LynnHo/AttGAN-Tensorflow#37]
Hello, after producing the pb model, how can i use it on a specific image?
I.e. i want to load a new image of mine, and i want to change my face by modifying my eyes.
Sorry for the probably supid question, but I didn't manage to understand how to apply the trained model to a specific brand new photo for appying some changes on it

thanks

**Comment by LynnHo** [comment]
@nablavectorgpu I didn't provide the code for a new image. A new face image should be aligned first (the code only handles aligned faces). You can refer to the data preparation part to find out how to align the faces and "test.py" for testing an aligned image.
