### ISSUE TITLE
The number of training images

### ISSUE THREAD

**Issue by FriedRonaldo** [LynnHo/AttGAN-Tensorflow#4]
Hello, I tried your code manually. While running, I found something strange. Following the command line, each epoch has 947 batches. It means that one epoch has only 947*batch_size(=32) = 30304 images.
Is that intended?(Because of the extremely slow training speed of WGAN-GP) or Did I made something wrong? I just copied a command lying on 'readme.md', training for 128x128 images
I checked a directory of 'img_align_celeba' in 'data' and text file already. And followed the manual that you kindly wrote on 'readme.md'

**Comment by FriedRonaldo** [comment]
Oh, this is my mistake. I did not consider WGAN-GP has n_critics=5. So, (180000/(32*6))~= 947

**Comment by LynnHo** [comment]
@FriedRonaldo Yes, you are right. One iteration contains 5 D updates and 1 G update. We have 182000 images for training, so 182000 // (32 * 6) = 947.

**Comment by FriedRonaldo** [comment]
@LynnHo Thank you for reply.. :) :+1:
