### ISSUE TITLE
Cannot get a desired result on CelebA-HQ dataset

### ISSUE THREAD

**Issue by EvaFlower** [LynnHo/AttGAN-Tensorflow#42]
Hi there,

Your work is interesting. I have a problem. Could you help figure it out?

I applied your method on CelebA-HQ dataset for a single attribute manipulation. But I cannot get the desired result. The result  (the interested attribute is "Smiling") at the 59th training epoch is shown as follows. There is no change in the third column images.
![attgan](https://user-images.githubusercontent.com/27620613/90994102-e97ba280-e5fa-11ea-976f-1e9c0bfb30bc.png)

Thanks and Regards,

**Comment by LynnHo** [comment]
@EvaFlower I haven't applied this code to CelebA-HQ, so I am not sure what's the problem. Have you tried the original CelebA on "Smiling"?

**Comment by EvaFlower** [comment]
@LynnHo 
I have not tried that.
For the limited computation, I applied it on the CelebA-HQ, which contains much fewer samples, to shorten the computation time. 
But anyway the CelebA-HQ is a high quality version of the subset of CelebA. Would it be possible due to insufficient samples?

Best,

**Comment by LynnHo** [comment]
@EvaFlower I will try this dataset in the spare time.

**Comment by LynnHo** [comment]
@EvaFlower I have tried CelebA-HQ. The results are not good enough, but it still works on 128 images (other resolutions are not tested). Please refer to the new README file.

Since fewer images of CelebA-HQ, more training loops are needed. You can use the command below for "Smiling",
```console
CUDA_VISIBLE_DEVICES=0 \
python train.py \
--img_dir ./data/CelebAMask-HQ/CelebA-HQ-img \
--train_label_path ./data/CelebAMask-HQ/train_label.txt \
--val_label_path ./data/CelebAMask-HQ/val_label.txt \
--load_size 128 \
--crop_size 128 \
--n_epochs 200 \
--epoch_start_decay 100 \
--model model_128 \
--experiment_name AttGAN_128_CelebA-HQ_Smiling \
--att_names Smiling
```

![image](https://user-images.githubusercontent.com/16457298/91178113-466c7b00-e717-11ea-9285-cc2487a2b5c6.png)
