### ISSUE TITLE
如何選取眼鏡樣式?

### ISSUE THREAD

**Issue by denny3366978** [LynnHo/AttGAN-Tensorflow#43]
您好~
我在ATTGAN裡面有看到可以選擇眼鏡的樣式，
請問這個程式可以透過任何方法自由選取眼鏡樣式嗎?
希望能得到您的幫助，非常感謝!

**Comment by LynnHo** [comment]
@denny3366978 你好，这个代码没有包括样式选择的功能，这个功能目前还没有加入开源代码的计划。

**Comment by denny3366978** [comment]
了解，謝謝您~
