### ISSUE TITLE
Attribute Style Manipulation

### ISSUE THREAD

**Issue by XijieJiao** [LynnHo/AttGAN-Tensorflow#44]
Hi, thank you for sharing the great project. I found your attribute style manipulation particularly meaningful and useful for my recent research. I saw from previous issue that you have no plan to open source the code for this part. I have the following questions:
1. I found nowhere in your paper as for how you derive your θ and the relationship between θ and the image, so how do you get the θ in an unsupervised way for each input?
2. Is this part's idea (and the way you derived θ) based on the paper 'Generative Attribute Controller with Conditional Filtered Generative Adversarial Networks'? (I found their code is also not open source).
3. If I want to realize this part myself, could you give me some hints of where to start or any papers and sources I could refer to (there is really very few works on accurate or multiple attribute style manipulation)?

Thank you!

**Comment by LynnHo** [comment]
@XijieJiao 

1. I am not sure that I understand your question. Do you mean the relationship between theta and x^a? They are independent, and theta is randomly sampled from a categorical distribution.

	![image](https://user-images.githubusercontent.com/16457298/93875483-a3078980-fd07-11ea-8277-af7926b24e22.png)

2. Yes, this idea is inspired by CF-GAN.

3. You can start by reproducing CF-GAN on "Bangs" style of CelebA, it's easy, just use AC-GAN with conditional filter. Or you can read this [repo](https://github.com/LynnHo/DTLC-GAN-Tensorflow), which is the implementation of DTLC-GAN (the next version of CF-GAN). But DTLC-GAN is more complicated on losses and conditional signals.

**Comment by XijieJiao** [comment]
Hi, thank you. I am now referring to your DTLC-GAN code but found something confusing. 

1. DTLC-GAN has no encoder, but a decoder and discriminator, right?
2. DTLC-GAN use two random vectors(z and c) as input and the images are only used in discriminator, so what should I do if I want to use a pretrained DTLC-GAN to generate results for an appointed image(generally speaking, how to run test for DTLC-GAN)?

Thank you.

**Comment by LynnHo** [comment]
@XijieJiao 

1. Yes.

2. DTLC-GAN generates images from z and c, but not for appointed images. You can read the DTLC-GAN paper for more details. If you wish to deal with appointed images, you could incorporate the DTLC-GAN idea into an image-to-image method (e.g., AttGAN-style incorporates CFGAN into AttGAN).

**Comment by XijieJiao** [comment]
Thank you.
