### ISSUE TITLE
How to calculate Attribute Preservation Error?

### ISSUE THREAD

**Issue by HyZhu39** [LynnHo/AttGAN-Tensorflow#49]
sorry for bothering, I think I couldn't find out how to calculate Attribute Preservation Error, could you please explain the specific calculation method of Attribute Preservation Error?

**Comment by LynnHo** [comment]
@HyZhu39 
1. For example, if your target attribute is "Eyeglasses", then ideally, the attribute difference before and after editing should only be "Eyeglasses". But if other attributes such as "Gender" changes, then an error happens.
2. For one target attribute, we edit this attribute on all testing images. Then, we compute the error rate of every other attribute, then average the error rate across all other attributes. The averaged error rate is the "Attribute Preservation Error" of this target attribute.

**Comment by HyZhu39** [comment]
> @HyZhu39
> 
> 1. For example, if your target attribute is "Eyeglasses", then ideally, the attribute difference before and after editing should only be "Eyeglasses". But if other attributes such as "Gender" changes, then an error happens.
> 2. For one target attribute, we edit this attribute on all testing images. Then, we compute the error rate of every other attribute, then average the error rate across all other attributes. The averaged error rate is the "Attribute Preservation Error" of this target attribute.

thanks for replying, I think I understand now.
