### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by ZLKong** [LynnHo/AttGAN-Tensorflow#5]
When I run the command :
CUDA_VISIBLE_DEVICES=0 \
python train.py \
--img_size 128 \
--shortcut_layers 1 \
--inject_layers 1 \
--experiment_name 128_shortcut1_inject1_none

It shows the error:
  File "train.py", line 269, in <module>
    save_path = saver.save(sess, '%s/Epoch_(%d)_(%dof%d).ckpt' % (ckpt_dir, epoch, it_in_epoch, it_per_epoch))
NameError: name 'it_in_epoch' is not defined

The process cannot get into the "try:"  in the train.py. It goes straight to "finally:". 
Do I have to add something?

**Comment by LynnHo** [comment]
@ZLKong Can you debug by step and find the error line? Or you can remove the try-catch-finally part and post the error here.

**Comment by ZLKong** [comment]
Thank you for your reply.
It can't get into the loop in line 223  "  for it in range(sess.run(it_cnt), max_it):  "
I tried to print out "sess.run(it_cnt)" and "max_it", they are both 189400. So the range is 0.
Can I change "sess.run(it_cnt)"  ?

**Comment by LynnHo** [comment]
@ZLKong Have you downloaded the pre-trained model? If yes, it_cnt is exactly the max_it. You can set larger "--epoch" value to continue the training or train the model from scratch by setting another "--experiment_name".

**Comment by ZLKong** [comment]
Ok, I see. Thank you very much!
