### ISSUE TITLE
stargan pretrained model

### ISSUE THREAD

**Issue by quancunzuicuo** [LynnHo/AttGAN-Tensorflow#50]
Hello, the official stargan model only includes 5 attributes. More attributes seem to have to be trained by myself. Where can I download the stargan pre-training model used in the AttGAN paper?

**Comment by LynnHo** [comment]
@quancunzuicuo Hi, I post the code and checkpoint of StarGAN ([Baidu Netdisk](https://pan.baidu.com/s/1l1gLvn96sJUaVPy_gvrAZQ), passwd: xm9v). However, it is not well organized enough and you should read some codes carefully.

Quick Test:

1. please follow [PA-GAN](https://github.com/LynnHo/PA-GAN-Tensorflow) to build the environment and prepare the data.
2. change the data path of `test.py` and run it.

**Comment by quancunzuicuo** [comment]
Thank you for your answer!
