### ISSUE TITLE
Applying your code in datasets from masked face to non-masked face

### ISSUE THREAD

**Issue by Nuha1412** [LynnHo/AttGAN-Tensorflow#51]
I want to apply this code on Celeb-A with fake masked images and i want to remove mask .. so how can i apply this concept .. can you guide me if i can do it or no using your code ?? if yes where should i change in the code just train.py and data.py ??

**Comment by 2076263413** [comment]
Do you  know how to do that?I also have a question of this.
![图片](https://user-images.githubusercontent.com/97661426/159152452-89ccb710-cc87-4bcb-bb76-abdee6ee1da1.png)
