### ISSUE TITLE
About design of model_348

### ISSUE THREAD

**Issue by NoctisZ** [LynnHo/AttGAN-Tensorflow#53]
Thank you very much for sharing the code and result! I noticed that for the model_348, the dimension of Conv layers is reduced (64 -> 48) and that of the FC layer is also set to half (1024 -> 512) compared with model_128. I'm pretty new to GAN and wonder if there's any specific reason(s) behind this hyperparameter design? Is it mainly because we want to speed up training by reducing the number of weights? Any information will be greatly appreciated.

**Comment by LynnHo** [comment]
@NoctisZ Just because I got OOM on my machine keeping conv-64 and fc-1024😭

**Comment by NoctisZ** [comment]
@LynnHo I see, that's reasonable haha. Thanks for the info!
