### ISSUE TITLE
How many shortcut/inject layers for high resolutions?

### ISSUE THREAD

**Issue by EoinKenny** [LynnHo/AttGAN-Tensorflow#54]
Hi, thank you for the excellent work!

I have been using your code for generating counterfactual images (e.g., changing 1 - > 7 on MNIST), and it works really well. My question is about the resolution and shortcut/inject layers.

When doing a resolution of 256, what number of shortcut/inject layers do you use? The default appears to be 1 for each, is that enough to get the results in the appendix of https://arxiv.org/pdf/1711.10678.pdf ?

The reconstructions are very good, so I am just surprised if these results come from just 1 shortcut layer. 

I ask because I am using this code for counterfactuals in medical images where have high resolution is very important, so I am wondering how you might modify the hyperparameters to ensure this? E.g., shortcut/inject layers, as well as epochs etc.

I know you're busy, so I just ask a simple question, thank you if you have time to reply!

**Comment by LynnHo** [comment]
We keep 1 shortcut layer for all experiments. If you want better reconstruction, use more shortcuts; but it harms the editing effects. You can also refer to https://github.com/csmliu/STGAN and https://github.com/LynnHo/PA-GAN-Tensorflow.

**Comment by EoinKenny** [comment]
Thanks a lot for that did you also use one inject layer in all experiments?

**Comment by LynnHo** [comment]
In module.py:

![image](https://github.com/LynnHo/AttGAN-Tensorflow/assets/16457298/e6fbd4c9-022f-4905-bc1f-ebb1b76d7c75)

**Comment by EoinKenny** [comment]
Got you just wanted to make sure thanks.
